# Generated by Django 5.2.6 on 2025-09-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="services/"),
        ),
    ]
